services:
  clickhouse:
    image: clickhouse/clickhouse-server:24.8
    container_name: clickhouse_hw
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./data:/data:ro
      - ./sql:/sql:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ["CMD", "clickhouse-client", "--query", "SELECT 1"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  clickhouse_data:
